# 主配置
spring.profiles.active=dev

# Jackson 配置
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.default-property-inclusion=non_null

# MVC 配置
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# 服务器配置
server.port=8080
server.servlet.context-path=/

# MyBatis-Plus 配置,一些通用的默认配置 直接用
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

# 日志配置
logging.config=classpath:logback-spring.xml